### ISSUE TITLE
Enable CORS on GraphQL API for access by browsers

### ISSUE THREAD

**Issue by ianengelbrecht** [rogerhyam/wfo-plant-list#6]
Hi, I tried to access the GraphQL API from a browser app in Chrome and get the following message

```
Access to fetch at 'https://list.worldfloraonline.org/gql.php' from origin 'http://localhost:5173' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```
It would be great to be able to access this without having to set up my own server to do so. 

Thanks!

**Comment by rogerhyam** [comment]
Hi Ian,

I'm having trouble reproducing this. I call the API from all over the place and don't generally have issues.

If I curl it with

`curl -I https://list.worldfloraonline.org/gql.php`

Then I get

```
HTTP/1.1 200 OK
Date: Mon, 29 Jan 2024 15:54:47 GMT
Server: Apache/2.4.52 (Ubuntu)
Access-Control-Allow-Origin: *
Set-Cookie: PHPSESSID=d128enk3r3ml8nmaurvbnrgbhq; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
```

Which has the magic `Access-Control-Allow-Origin: *` in it.

I wrote a test file (attached) which just calls the API. Popped it in a folder and ran the PHP internal server in that folder with the port number you are using just to double check.

php -S localhost:5173

And it works fine with no CORs error. 

[testing_cors.zip](https://github.com/rogerhyam/wfo-plant-list/files/14086647/testing_cors.zip)

Can you give me any more details?

**Comment by ianengelbrecht** [comment]
This slipped through the cracks, let me look at it again and get back to you.

**Comment by ianengelbrecht** [comment]
Okay I ran the example file you sent without any problems. I don't have the code that was giving the issue I had any longer, but if I remember correctly I was trying to use some kind of graphql client. That shouldn't have made a difference though. Closing...

**Comment by rogerhyam** [comment]
Funnily enough just the other day I did run into an issue in that I do not specify cors access-control-allow-headers so if you are asking for a specific content type you might get rejected but if you don't specify a accepted content type it won't break. This might be me being incorrect but I'm frightened to touch it incase I start breaking other stuff - it works with multiple GraphQL clients at the moment. Cors can be a complete pain!

**Comment by ianengelbrecht** [comment]
Cors is absolutely horrible! So many many hours spent trying to make it work. 

I just want to say the GraphQL API is fantastic though, so helpful and versatile. I hope for biodiversity informatics platforms will adopt GraphQL in future, and I regularly point people to this one as an example of how it should be done.
